localrep: /etc/yum.repos.d/
repos:
    - {
          name: "docker-ce",
          file: docker-ce.repo,
          url: "https://download.docker.com/linux/centos/docker-ce.repo",
          type: "web",
      }
services_add:
    - docker
group_add:
    - docker
packages:
    - { name: "docker-ce" }
    - { name: "docker-ce-cli" }
    - { name: "containerd.io" }