- name: settingshost
  hosts: all
  become: yes

  tasks:

#  - set_fact:
#      hostmessage: "{{paternname}}{{itemnum+groups[groupdef].index(inventory_hostname)+1}}"

  - name: rename hostname
    hostname:
      name: "{{hostnamenew}}"

  - name: Reboot host
    reboot:

  - name: Dhcp restart
    shell: dhclient -r; dhclient -v eth0 -H "{{hostnamenew}}"

  - name: Reboot host
    reboot:
