---
- name: HAProxy start
  hosts: all
  become: yes
  gather_facts: yes

  vars:
    packet: haproxy
    service: haproxy
    pathconfig: /etc/haproxy/haproxy.cfg

  tasks:
    - name: Install HAProxy
      yum:
        pkg: "{{packet}}"
        state: present
    
    - name: Service Start HAProxy
      systemd:
        service: "{{service}}"
        enabled: yes
        state: started

    - name: Update files
      lineinfile:
        path: "{{pathconfig}}"
        line: 'frontend my_http
                bind *:80'
        backup: yes