---
- name: HAProxy start
  hosts: all
  become: yes
  gather_facts: yes

  vars:
    packet: haproxy
    service: 
           - haproxy
           - rsyslog
    pathconfiglocal: ./haproxy.cfg
    pathconfig: /etc/haproxy/haproxy.cfg
    pathsyslog: /etc/rsyslog.conf
    pathconfloghaproxy: /etc/rsyslog.d/haproxy.conf
    linepathsyslog:
                  - ^#\$ModLoad imudp
                  - ^#\$UDPServerRun 514

  tasks:
    - name: Install HAProxy
      yum:
        pkg: "{{packet}}"
        state: present
    
    - name: Service Start HAProxy
      systemd:
        service: "{{item}}"
        enabled: yes
        state: started
      loop: "{{service}}"

    - name: copy file haproxy
      copy:
        src: "{{pathconfiglocal}}"
        dest: "{{pathconfig}}"
        backup: yes

    - name: Setting rsyslog update
      replace:
        path: "{{pathsyslog}}"
        #regexp: "{{item}}"
        regexp: '^#\$ModLoad imudp'
        replace: '\1'
      #loop: "{{linepathsyslog}}"

    - name: Setting rsyslog add
      lineinfile:
        path: "{{pathsyslog}}"
        line: $UDPServerAddress 127.0.0.1
        backup: yes

    - name: Setting rsyslog haproxy log
      lineinfile:
        path: "{{pathconfloghaproxy}}"
        line: local2.* /var/log/haproxy.log
        create: yes

    - name: service restart
      systemd:
        service: "{{item}}"
        state: restarted
        daemon_reload: yes
      loop: "{{service}}"



