- block:
    - set_fact:
        masterserver: "{{hostvars['master'].ansible_hostname}}"
    - name: Copy File kubeadmjoin.sh
      become: no
      template:
        src: ./kubeadmjoin.j2
        dest: ~/kubeadmjoin.sh
        mode: "0755"
        

    - name: Add kub worker
      shell: /home/{{ansible_user}}/kubeadmjoin.sh

    - name: Reboot Worker
      reboot:

  when: role == "worker"
