- block:
    - name: Copy File kubeadminit.sh
      become: no
      template:
        src: ./kubeadminit.j2
        dest: ~/kubeadminit.sh
        mode: "0755"

    - name: copy admin.conf to user's kube config
      become: no
      copy:
        src: config.yaml
        dest: ~/
        mode: "0755"
        #owner: "{{ansible_user}}"

    - name: kubeadm initial
      shell: /home/{{ansible_user}}/kubeadminit.sh

    - name: Create kube directory
      become: no
      file:
        path: "~/.kube"
        state: directory
        mode: "0750"

    - name: copy admin.conf to user's kube config
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/{{ansible_user}}/.kube/config
        remote_src: yes
        mode: "0750"
        owner: "{{ansible_user}}"

    - name: Download web file kubsubnet
      become: no
      get_url:
        url: "{{item.path}}"
        dest: "~/{{item.name}}"
      loop: "{{kubsubnet}}"
      when: item.type == "web"

    - name: Download file kubsubnet
      become: no
      copy:
        src: "{{item.path}}"
        dest: "~/{{item.name}}"
      loop: "{{kubsubnet}}"
      when: item.type == "file"

    - name: kubectl apply subnet
      become: no
      shell: "kubectl apply -f ~/{{item.name}}"
      loop: "{{kubsubnet}}"

  when: role == "master"