---
# tasks file for k8s-project

#  - name: Copy
#    template:
#      src: filetest.j2
#      dest: /tmp/
#      mode: 0600

- name: Add docker-ce
  yum_repository:
    name: "{{item.name}}"
    description: "{{item.description}}"
    baseurl: "{{item.url}}"
    file: "{{item.file}}"
  loop: "{{repos}}"

- name: Install packages
  yum:
    pkg: "{{packages}}"
    state: present
