---
# tasks file for k8s-project
#  - name: Copy
#    template:
#      src: filetest.j2
#      dest: /tmp/
#      mode: 0600

- include: install.yml
- include: createmaster.yml
- include: createworker.yml