---
# tasks file for k8s-project

#  - name: Copy
#    template:
#      src: filetest.j2
#      dest: /tmp/
#      mode: 0600
- name: Download repo
  get_url:
    url: "{{item.url}}"
    dest: "/etc/yum.repos.d/{{item.file}}"
  loop: "{{repos}}"

- name: Install packages
  yum:
    pkg: "{{packages}}"
    state: present
    disable_gpg_check: yes
