---
# tasks file for k8s-project
#  - name: Copy
#    template:
#      src: filetest.j2
#      dest: /tmp/
#      mode: 0600
- name: Download web repo
  get_url:
    url: "{{item.url}}"
    dest: "{{localrep}}{{item.file}}"
  loop: "{{repos}}"
  when: item.type == "web"

- name: Download file repo
  copy:
    src: "{{item.file}}"
    dest: "{{localrep}}{{item.file}}"
  loop: "{{repos}}"
  when: item.type == "file"

- name: Install packages
  yum:
    pkg: "{{item.name}}"
    state: present
    disable_gpg_check: yes
  loop: "{{packages}}"
  when: role == "master" or item.type == role

- name: modprobe command
  modprobe:
    name: "{{item}}"
    state: present
  loop:
    - overlay
    - br_netfilter

- name: Create Copy File
  copy:
    src: "{{item.source}}"
    dest: "{{item.dest}}"
  loop: "{{filecopy}}"

- name: sysctl command
  shell: sysctl --system

- name: service add enable start
  systemd:
    service: "{{item}}"
    enabled: yes
    state: started
  loop: "{{services_add}}"

- name: Create groups
  group:
    name: "{{item}}"
    state: present
  loop: "{{group_add}}"

- name: Off SWAP
  shell: swapoff -a

- name: Setting swap fstab.
  replace:
    path: /etc/fstab
    regexp: "^{{swaptextmount}}"
    replace: "#{{swaptextmount}}"
  
  
- block:

  - name: Copy File kubeadminit.sh
    become: no
    template:
      src: ./kubeadminit.j2
      dest: ~/kubeadminit.sh
      mode: "0755"
  
  - name: copy admin.conf to user's kube config
    become: no
    copy:
      src: config.yaml
      dest: ~/
      mode: "0755"
      #owner: "{{ansible_user}}"
  
  - name: kubeadm initial
    shell: /home/{{ansible_user}}/kubeadminit.sh
  
  - name: Create kube directory
    become: no
    file:
      path: "~/.kube"
      state: directory
      mode: "0750"
 
  - name: copy admin.conf to user's kube config
    copy:
      src: /etc/kubernetes/admin.conf
      dest: /home/{{ansible_user}}/.kube/config
      remote_src: yes
      mode: "0750"
      owner: "{{ansible_user}}"
  
  - name: Download web file kubsubnet
    become: no
    get_url:
      url: "{{item.path}}"
      dest: "~/{{item.name}}"
    loop: "{{kubsubnet}}"
    when: item.type == "web"
  
  - name: Download file kubsubnet
    become: no
    copy:
      src: "{{item.path}}"
      dest: "~/{{item.name}}"
    loop: "{{kubsubnet}}"
    when: item.type == "file"

  - name: kubectl apply subnet
    become: no
    shell: "kubectl apply -f ~/{{item.name}}"
    loop: "{{kubsubnet}}"
  
  - set_fact:
      masterhost: "{{ansible_hostname}}"

  when: role == "master1"

- block:
  - set_fact:
      masterhost: "{{ansible_hostname}}"

  when: role == "master"

- block:

  - name: Copy File kubeadmjoin.sh
    template:
      src: ./kubeadmjoin.j2
      dest: ~/kubeadmjoin.sh
      mode: "0755"
      become: no

  - name: find several related variables
    debug: 
      msg: "{{ lookup('masterhost', 'ansible_play_hosts_all') }}"

  #- name: Add kub worker
  #  shell: ~/kubeadmjoin.sh

  when: role == "worker"



