- name: Create group jenkins
  group:
    name: "{{userj}}"
    state: present
    gid: "{{idguserj}}"

- name: Create user jenkins
  user:
    name: "{{userj}}"
    uid: "{{idguserj}}"
    comment: jenkins

- name: Create a directory
  file:
    path: "{{homejenkins}}"
    state: directory
    mode: "0775"
    owner: "{{userj}}"
    group: "{{userj}}"

- name: Install packages
  yum:
    pkg: "{{item.name}}"
    state: present
    disable_gpg_check: yes
  loop: "{{packages}}"

- name: Install packages PIP
  pip:
    name: "{{item.name}}"
  loop: "{{packages_pip}}"

- name: application container
  docker_container:
    name: jenkinsapp
    image: "{{packetj}}"
    state: started
    user: "{{idguserj}}:{{idguserj}}"
    restart_policy: always
    privileged: yes
    #volumes:
    #  - "jenkins-data:{{homejenkins}}"
    #  - "jenkins-docker-certs:{{crtjenkins}}"
    ports:
      - "8080:8080"
      - "50000:50000"
    mounts:
      - { labels: jenkins-data, source: "{{homejenkins}}", type: volume, target: "{{homejenkins}}"}
      - { labels: jenkins-docker-certs, type: volume , target: "{{crtjenkins}}"}
    networks:
      - { name: jenkins, aliases: docker }
