- name: Create user jenkins
  user:
    name: "{{userj}}"
    comment: jenkins

- name: Create a directory
  file:
    path: "{{homejenkins}}"
    state: directory
    mode: '0775'
    owner: "{{userj}}"
    group: "{{userj}}"

- name: Install packages
  yum:
    pkg: "{{item.name}}"
    state: present
    disable_gpg_check: yes
  loop: "{{packages}}"

- name: Install packages PIP
  pip:
    name: "{{item.name}}"
  loop: "{{packages_pip}}"

- name: application container
  docker_container:
    name: jenkinsapp
    image: "{{packetj}}"
    state: started
    user: "{{userj}}:{{userj}}"
    restart_policy: always
    devices:
           - "{{homejenkins}}:{{homejenkins}}"
    ports:
           - "8080:8080"
           - "50000:50000"