- name: Create a directory
  file:
    path: "{{homejenkins}}"
    state: directory
    mode: '0755'

- name: application container
  docker_container:
    name: jenkinsapp
    image: jenkins/jenkins
    state: started
    restart_policy: always
    devices:
           - "jenkins_home:/var/jenkins_home:rwm"
    ports:
           - "8080:8080"
           - "50000:50000"