- name: Create a directory
  file:
    path: "{{homejenkins}}"
    state: directory
    mode: '0755'

- name: Install packages
  yum:
    pkg: "{{item.name}}"
    state: present
    disable_gpg_check: yes
  loop: "{{packages}}"

- name: Install packages PIP
  pip:
    name: "{{item.name}}"
  loop: "{{packages_pip}}"

- name: application container
  docker_container:
    name: jenkinsapp
    image: jenkins/jenkins
    state: started
    restart_policy: always
    devices:
           - "jenkins_home:/var/jenkins_home"
    ports:
           - "8080:8080"
           - "50000:50000"