---
# tasks file for k8s-project
#  - name: Copy
#    template:
#      src: filetest.j2
#      dest: /tmp/
#      mode: 0600

- include: installall.yml

- include: installmaster.yml
  when: role == "master"

- include: installslave.yml
  when: role == "slave"