- name: label kub worker
  shell: kubectl label node {{item}} node-role.kubernetes.io/worker=worker --overwrite
  with_items: "{{ groups['all'] }}"
  when: item != 'master'

- name: images pull
  become: yes
  shell: kubeadm config images pull

- name: copy yaml
  copy:
    src: "{{item}}"
    dest: ~/
    mode: "0755"
  loop: "{{mypods}}"

- name: test docker
  debug: 
    var: docker_username

- name: docker login
  shell: "docker login -u {{docker_username}} -p {{docker_password}}"

- name: Copy File template sh
  template:
    src: "./{{item}}.j2"
    dest: "~/{{item}}.sh"
    mode: "0755"
  loop: "{{mytemplates}}"

- name: shell kubectl
  shell: "~/{{item}}.sh"
  register: fail_me
  failed_when: "'AlreadyExists' not in fail_me.stderr and fail_me.rc != 0"
  loop: "{{mytemplates}}"

- name: images pods create
  shell: "kubectl apply -f ~/{{item}}"
  loop: "{{mypods}}"