- name: label kub worker
  shell: kubectl label node {{item}} node-role.kubernetes.io/worker=worker --overwrite
  with_items: "{{ groups['all'] }}"
  when: item != 'master'

- name: images pull
  become: yes
  shell: kubeadm config images pull