- name: label kub worker
  shell: kubectl label node {{item}} node-role.kubernetes.io/worker=worker --overwrite
  with_items: "{{ groups['all'] }}"
  when: item != 'master'

- name: images pull
  become: yes
  shell: kubeadm config images pull

- name: copy mypods.yaml
  become: no
  copy:
    src: mypods.yaml
    dest: ~/
    mode: "0755"

- name: test docker
  debug: 
    var: docker_username

#- name: docker login
#  shell: kubectl apply -f ~/mypods.yaml

- name: images pull
  shell: kubectl apply -f ~/mypods.yaml