apiVersion: v1
kind: Pod
metadata:
  name: mywebapp
  labels:
    env : prom
    app : main
    owner: MY
spec:
  containers:
  - name: container-myapache
    image: mazahakq/myapache:latest
    ports:
      - containerPort: 80
  - name: container-tomcat
    image: tomcat:latest
    ports:
      - containerPort: 8080
  imagePullSecrets:
  - name: regcred